# Documentation: https://docs.codecov.io/docs/codecov-yaml

codecov:
  notify:
    after_n_builds: 1  # send notifications after the first upload
  bot: dlang-bot

coverage:
  precision: 3
  round: down
  range: "70...100"

  # Learn more at https://docs.codecov.io/docs/commit-status
  status:
    project:
      default:
        informational: true
        # Informational doesn't work with project yet
        threshold: 0.1
    patch:
      default:
        informational: true
    changes:
      default:
        informational: true

  notify:
    webhook:
      default:
        url: "https://dlang-bot.herokuapp.com/codecov_hook"

comment: false
